# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


'902', '904', '908', '920', '921', '922', '923', '924', '925', '926',
'927', '928', '929', '930', '931', '932', '933', '835', '934', '936',
'937', '938', '939', '950', '951', '999'